name: Coverage Reporter

on: ["push"]

jobs:
  coverage-reporter:
    runs-on: ubuntu-latest
    name: coverage-reporter
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install and build libraries
        run: |
            pnpm install --frozen-lockfile
            pnpm build
      - name: Run coverage-reporter
        run: |
            export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
            bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
